# columns to check for 15 minute data along with their thresholds
thresholds_15 = {
    "Air_T": 8,
    "RH": 96,
    "Pluvio_Rain": 10,
    "AvgWS": 5,
    "AvgWD": 5,
    "AvgSD": 5,
    "TBRG_Rain": 10,
    "MaxWS": 5,
    "Press_hPa": 96,
}

# columns to check for 60 minute data along with their thresholds
# note: excludes soil temp/moisture at 50/100cm because values are stable at those depths
thresholds_60 = {
    "Air_T": 5,
    "AvgAir_T": 5,
    "MaxAir_T": 5,
    "MinAir_T": 5,
    "RH": 24,
    "AvgRH": 24,
    "Pluvio_Rain": 5,
    "WS_10Min": 5,
    "WD_10Min": 5,
    "AvgWS": 5,
    "AvgWD": 5,
    "AvgSD": 5,
    "MaxWS_10": 5,
    "MaxWD_10": 10,
    "MaxWS": 5,
    "MaxWD": 5,
    "Max5WS_10": 5,
    "Max5WD_10": 5,
    "WS_2Min": 5,
    "WD_2Min": 5,
    "Soil_T05": 24,
    "AvgRS_kw": 5,
    "TotRS_MJ": 5,
    "TBRG_Rain": 5,
    "Soil_TP5_TempC": 48,
    "Soil_TP5_VMC": 24,
    "Soil_TP20_TempC": 24,
    "Soil_TP20_VMC": 24,
    "Evap60": 24,
    "SolarRad": 5,
    "Press_hPa": 24
}

# columns to check for 24 hour data along with their thresholds
# note: no Hm columns
thresholds_24 = {
    "AvgAir_T": 3,
    "MaxAir_T": 3,
    "MinAir_T": 3,
    "AvgRH": 5,
    "MaxRH": 30,
    "MinRH": 5,
    "Pluvio_Rain": 3,
    "MaxWS": 3,
    "AvgWS": 3,
    "AvgWD": 3,
    "AvgSD": 3,
    "AvgSoil_T05": 10,
    "MaxSoil_T05": 10,
    "MinSoil_T05": 10,
    "AvgRS_kw": 3,
    "MaxRS_kw": 3,
    "TotRS_MJ": 3,
    "TBRG_Rain": 3,
    "Avg_Soil_TP5_TempC": 10,
    "Max_Soil_TP5_TempC": 10,
    "Min_Soil_TP5_TempC": 10,
    "Avg_Soil_TP5_VMC": 5,
    "Max_Soil_TP5_VMC": 5,
    "Min_Soil_TP5_VMC": 5,
    "Avg_Soil_TP20_TempC": 10,
    "Max_Soil_TP20_TempC": 10,
    "Min_Soil_TP20_TempC": 10,
    "Avg_Soil_TP20_VMC": 5,
    "Max_Soil_TP20_VMC": 5,
    "Min_Soil_TP20_VMC": 5,
    "Avg_Soil_TP50_TempC": 15,
    "Max_Soil_TP50_TempC": 15,
    "Min_Soil_TP50_TempC": 15,
    "Avg_Soil_TP50_VMC": 15,
    "Max_Soil_TP50_VMC": 15,
    "Min_Soil_TP50_VMC": 15,
    "Avg_Soil_TP100_TempC": 15,
    "Max_Soil_TP100_TempC": 15,
    "Min_Soil_TP100_TempC": 15,
    "Avg_Soil_TP100_VMC": 15,
    "Max_Soil_TP100_VMC": 15,
    "Min_Soil_TP100_VMC": 15,
    "EvapTot24": 3
}